site_name: Cil2bsb

theme:
    name: material
    favicon: images/logo-cil-2.png
    logo: images/logo-cil-2.png

    language: pt
    features:
        - header.autohide
        - navigation.tabs
nav:
    - Home: index.md
    - Apresentações:
          - Apresentação 01: 'Apresentacao/Apresentacao_1/apresentacao1.md'
          - Apresentação 02: 'Apresentacao/apresentacao2.md'
          - Apresentação 03: 'Apresentacao/apresentacao3.md'
          - Apresentação 04: 'Apresentacao/apresentacao4.md'
          - Apresentação 05: 'Apresentacao/apresentacao5.md'
          - Apresentação 06: 'Apresentacao/apresentacao6.md'
    - Planejamento:
          - Planejamento: 'Planejamento/Planejamento.md'
          - Processo de Design: 'Planejamento/processo-de-design.md'
    - Análise de requisitos:
          - Análise do Perfil de Usuário:
                - Análise de tarefas: 'Analise_Requisitos/tarefas.md'
                - Perfil do Usuário: 'Analise_Requisitos/perfil_usuario.md'
                - Personas: 'Analise_Requisitos/personas.md'
          - Princípios Gerais de Projeto: 'Analise_Requisitos/principios_gerais.md'
          - Características da Plataforma: 'Analise_Requisitos/carac_plataforma.md'
          - Metas de Usabilidade: 'Analise_Requisitos/metas_usabilidade.md'
          - Guia de Estilo: 'Analise_Requisitos/guia_estilo.md'
    - Design, Avaliação e Desenvolvimento:
          - Nível 1:
                - Análise de tarefas:
                      - Planejamento da Avaliação da Análise de Tarefas: 'Design_avaliacao_desenvolvimento/planejamento_analise_tarefas.md'
                      - Teste Piloto da Avaliação da Análise de Tarefas: 'Design_avaliacao_desenvolvimento/teste_piloto_tarefa.md'
                      - Avaliação da Análise de Tarefas: 'Design_avaliacao_desenvolvimento/avaliacao_analise_tarefas.md'
                - Storyboard:
                      - Storyboard: 'Design_avaliacao_desenvolvimento/storyboard.md'
                      - Planejamento da Avaliação do Storyboard: 'Design_avaliacao_desenvolvimento/planejamento_storyboard.md'
                      - Teste Piloto da Avaliação do Storyboard: 'Design_avaliacao_desenvolvimento/teste_piloto_storyboard.md'
                      - Avaliação do Storyboard: 'Design_avaliacao_desenvolvimento/avaliacao_storyboard.md'
          - Nível 2:
                - Protótipo de Baixa-fidelidade: 'Design_avaliacao_desenvolvimento/prototipo_baixa_fidelidade.md'
                - Planejamento da Avaliação do Protótipo de Baixa-fidelidade: 'Design_avaliacao_desenvolvimento/planejamento_prototipo.md'
                - Teste Piloto do Protótipo de Baixa-fidelidade: 'Design_avaliacao_desenvolvimento/teste_piloto_prototipo.md'
                - Avaliação do Protótipo de Baixa-Fidelidade: 'Design_avaliacao_desenvolvimento/avaliacao_baixa_fidelidade.md'
          - Nível 3:
                - Protótipo de Alta-Fidelidade: 'Design_avaliacao_desenvolvimento/prototipo_alta_fidelidade.md'
                - Planejamento da Avaliação do Protótipo de Alta-fidelidade: 'Design_avaliacao_desenvolvimento/planejamento_prototipo_altafidelidade.md'
                - Teste Piloto do Protótipo de Alta-fidelidade: 'Design_avaliacao_desenvolvimento/teste_piloto_prototipo_alta_fidelidade.md'
                - Avaliação do Protótipo de Alta-Fidelidade: 'Design_avaliacao_desenvolvimento/avaliacao_alta_fidelidade.md'
    - Verificação:
          - Análise de requisitos:
                - Análise do Perfil de Usuário:
                      - Análise de tarefas: 'Verificacao/AnaliseRequisitos/AnalisePerfil/analise_tarefas.md'
                      - Perfil do Usuário: 'Verificacao/AnaliseRequisitos/AnalisePerfil/perfil_usuario.md'
                      - Personas: 'Verificacao/AnaliseRequisitos/AnalisePerfil/personas.md'
                - Princípios Gerais de Projeto: 'Verificacao/AnaliseRequisitos/principios_gerais.md'
                - Características da Plataforma: 'Verificacao/AnaliseRequisitos/caracteristicas.md'
                - Metas de Usabilidade: 'Verificacao/AnaliseRequisitos/metas_usabilidade.md'
                - Guia de Estilo: 'Verificacao/AnaliseRequisitos/guia_estilo.md'
          - Design, Avaliação e Desenvolvimento:
                - Nível 1:
                      - Análise de tarefas:
                            - Planejamento da Avaliação da Análise de Tarefas: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/planejamento_analise.md'
                            - Teste Piloto da Avaliação da Análise de Tarefas: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/teste_analise.md'
                            - Avaliação da Análise de Tarefas: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/avaliacao_tarefas.md'
                      - Storyboard:
                            - Storyboard: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/storyboard.md'
                            - Planejamento da Avaliação do Storyboard: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/planejamento_storyboard.md'
                            - Teste Piloto da Avaliação do Storyboard: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/teste_storyboard.md'
                            - Avaliação do Storyboard: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/avaliacao_storyboard.md'
                - Nível 2:
                      - Protótipo de Baixa-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel2/prototipo_baixa.md'
                      - Planejamento da Avaliação do Protótipo de Baixa-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel2/planejamento_baixa.md'
                      - Teste Piloto da Avaliação do Protótipo de Baixa-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel2/teste_baixa.md'
                      - Avaliação do Protótipo de Baixa-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel2/avaliacao_baixa.md'
                - Nível 3:
                      - Protótipo de Alta-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel3/prototipo_alta.md'
                      - Planejamento da Avaliação do Protótipo de Alta-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel3/planejamento_alta.md'
                      - Teste Piloto da Avaliação do Protótipo de Alta-fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel3/teste_alta.md'
                      - Avaliação do Protótipo de Alta-Fidelidade: 'Verificacao/DesignAvaliacaoDesenvolvimento/Nivel3/avaliacao_alta.md'
docs_dir: docs/
